### ISSUE TITLE
Puste wartości

### ISSUE THREAD

**Issue by Pt47-112** [KulaKrzysztof/GUS-API---PHP#1]
Chciałem skorzystać z tej biblioteki, bo wygląda na prostą i przejrzystą, jednak zwraca mi puste wartości (NULL). Analizując poszczególne kroki, to chyba już na etapie logowania jest coś nie tak, bo funkcja login zwraca false. Zarówno dla klucza i adresów testowych jak i produkcyjnych.

Co robię źle?

**Comment by studiomoyoki** [comment]
Może spróbuj przełączyć z testowych na produkcyjne urle. Mi zadziałało.

**Comment by de-vile** [comment]
Na testowych URL-ach logujesz sie z testowym kluczem API - takim jaki jest wpisany w bibliotece. Logowanie z innym kluczem zwróci fałsz. Czyli zadziałało poprawnie. Zgodnie z dokumentacją GUSAPI. Dopiero na roboczych serwerach, logujesz się już z własnym kluczem.

**Comment by KulaKrzysztof** [comment]
> Na testowych URL-ach logujesz sie z testowym kluczem API - takim jaki jest wpisany w bibliotece. Logowanie z innym kluczem zwróci fałsz. Czyli zadziałało poprawnie. Zgodnie z dokumentacją GUSAPI. Dopiero na roboczych serwerach, logujesz się już z własnym kluczem.

Potwierdzam, do danych testowych są inne dane logowania.
