### ISSUE TITLE
Brak numeru ulicy

### ISSUE THREAD

**Issue by piotrekd1** [KulaKrzysztof/GUS-API---PHP#2]
Dane jakie pobiera nie zawierają numeru ulicy. Czy można coś z tym zrobić?

**Comment by de-vile** [comment]
Dane testowe róznią się od danych roboczych. Dane robocze są bezpośrednio pobierane z bazy regon i są identyczne jak w bazie regon.

**Comment by pw031** [comment]
Cześć, niekoniecznie. Adresy produkcyjne też zwracają dane bez numeru lokalu czy nieruchomości.

**Comment by pw031** [comment]
Rozwiązałem problem.
searchURL jest użyta metoda "daneSzukaj". 
Trzeba zmienić metodę na "DaneSzukajPodmioty"

I działa jak należy.

**Comment by szojox** [comment]
> Rozwiązałem problem. searchURL jest użyta metoda "daneSzukaj". Trzeba zmienić metodę na "DaneSzukajPodmioty"
> 
> I działa jak należy.

Dzięki, nigdzie nie mogłem tego znaleźć
