### ISSUE TITLE
Problem z pobieraniem

### ISSUE THREAD

**Issue by barii86** [KulaKrzysztof/GUS-API---PHP#3]
Kiedy wysyłam zapytanie do bazy GUS, odpowiedź nie zawsze jest zwracana poprawnie. Co jakiś czas tylko mam zwrotnego JSONa z danymi. W czym może być problem.

Czy nie zaszły jakieś zmiany w dostępach lub składni skryptu?

**Comment by KulaKrzysztof** [comment]
Serwery testowe nie odpowiadają na wszystkie numery NIP.
