### ISSUE TITLE
Brak danych po wprowadzeniu klucza z GUS

### ISSUE THREAD

**Issue by qman-web-development** [KulaKrzysztof/GUS-API---PHP#4]
Witam,
gdy pobieram dane z url i klucza testowego wszystko działa pięknie i dostaje w zwrocie dane firmy testowej, jednak gdy użyje klucza otrzymanego od GUS i adresy produkcyjne w ogóle nie zwraca żadnych danych :(  Sprawdzałem poprawność  klucza chyba ze sto razy i na pewno jest dobrze wpisany jednak po wysłaniu requesta pod https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj zwraca puste dane :(

**Comment by KulaKrzysztof** [comment]
A IP serwera zgadza się z tym zgłoszonym w GUS?

**Comment by PiotrCzarnik** [comment]
Dzień dobry ;
Panie Krzysztofie na wstępie słowo uznania : świetny , prosty kod .
Mam niestety ten sam problem co kolega wyżej , test działa prawidłowo , ale produkcja niestety nie .
Nie mam jak sprawdzić klucza , programista z GUS stwierdził ,że jest ok , IP serwera reż podałem prawidłowo .
Jaka może być inna przyczyna , może coś w adresach wsdl ?
Poniżej instrukcja przekazana przez GUS 👍 
Aktualna dokumentacja:

https://api.stat.gov.pl/Home/RegonApi (zakładka "Instrukcja")
Adres usługi BIR1.1, wersja produkcyjna
https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc

Adres wsdl:
https://wyszukiwarkaregon.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl-ver11-prod.wsdl
Dostęp do usługi BIR1/BIR1.1 jest bezpłatny, bez ograniczenia czasowego.
Klucz użytkownika pozwala na dostęp zarówno do wersji BIR1.1 jak i BIR1.
// **************************************************************************************** //

Informacje dodatkowe - dot. wersji testowej BIR1.1
BIR1.1 wersja testowa
Adres usługi:
https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc

Adres wsdl:
https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl-ver11-test.wsdl
Klucz:
abcde12345abcde12345
// **************************************************************************************** //
Informacje dodatkowe - dot. BIR1 (1.0)
BIR1 wersja produkcyjna, adres Usługi:
https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc
BIR1 wersja testowa, adres Usługi:
https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc

BIR1 wsdl (wspólny dla BIR1 TEST i BIR1 PROD; dla PROD wymagana zmiana opisana w BIR1_Przyklady.docx, pkt.4)
https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd
klucz:
abcde12345abcde12345

**Comment by KulaKrzysztof** [comment]
Dzień dobry,
Proszę sprawdzić jeszcze adres w metodzie login - domyślnie podany jest adres testowy.

`$result = $this->makeCurl($login, $this->loginUrl);`

Sam teraz sprawdziłem z moim kluczem skrypt i jest wszystko ok - dostaję w odpowiedzi klucz sesji.

**Comment by PiotrCzarnik** [comment]
Panie Krzysztofie , poniżej cały mój kod , jeżeli może Pan to proszę zerknąć .
Proszę też o adres na priv to wyślę mój klucz api .

<?php
$nip = '1130089950';
$gus = new GusRegonApi();
$result = $gus->checkNip($nip);
echo $result;

class GusRegonApi{
//adresy produkcyjne
    protected $loginUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
    protected $searchDataUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';
    //adresy testowe
    protected $loginTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
    protected $searchDataTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';
    
    //tutaj wpisan klucz do GUS - obecnie testowy
    protected $key = "c2fb8716344a4672852f"; // "abcde12345abcde12345"; 
    protected $session = null;

    protected function makeCurl($field,$url){
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $field);
        curl_setopt($curl, CURLOPT_ENCODING, 'UTF-8');
        curl_setopt($curl, CURLOPT_HTTPHEADER, ['Content-Type: application/json','Content-Length: '.strlen($field), 'sid:'.$this->session]);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_TIMEOUT, 10);
        curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36');
        curl_setopt($curl, CURLOPT_HEADER, false);
        $result = curl_exec($curl);
        curl_close($curl);
        if($this->session==null){
            return json_decode($result)->d;
        }else{
            return str_replace('\u000d\u000a','',$result);
        }
    }

    protected function login(){
        $login = json_encode(["pKluczUzytkownika" => $this->key]);
        $result = $this->makeCurl($login, $this->loginUrl);
        return $result;
    }

    public function checkNip($nip){

        if($this->session==null){
            $this->session = $this->login();
        }



        $searchData = json_encode([
            'jestWojPowGmnMiej' => true,
            'pParametryWyszukiwania' => [
                'AdsSymbolGminy' => null,
                'AdsSymbolMiejscowosci' => null,
                'AdsSymbolPowiatu' => null,
                'AdsSymbolUlicy' => null,
                'AdsSymbolWojewodztwa' => null,
                'Dzialalnosci' => null,
                'FormaPrawna' => null,
                'Krs' => null,
                'Krsy' => null,
                'NazwaPodmiotu' => null,
                'Nip' => $nip,
                'Nipy' => null,
                'NumerwRejestrzeLubEwidencji' => null,
                'OrganRejestrowy' => null,
                'PrzewazajacePKD' => false,
                'Regon' => null,
                'Regony14zn' => null,
                'Regony9zn' => null,
                'RodzajRejestru' => null,
                ]
            ]
        );

        $result = $this->makeCurl($searchData,$this->searchDataUrl);
        return $result;
    }


}

?>

**Comment by PiotrCzarnik** [comment]
Panie Krzysztofie poniżej mój kod , proszę też o adres priv to prześlę mój klucz api .
`<?php
$nip = '1130089950';
$gus = new GusRegonApi();
$result = $gus->checkNip($nip);
echo $result;

class GusRegonApi{
//adresy produkcyjne
    protected $loginUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
    protected $searchDataUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';
    //adresy testowe
    protected $loginTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
    protected $searchDataTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';
    
    //tutaj wpisan klucz do GUS - obecnie testowy
    protected $key = "c2fb8716344a4672852f"; // "abcde12345abcde12345"; 
    protected $session = null;

    protected function makeCurl($field,$url){
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $field);
        curl_setopt($curl, CURLOPT_ENCODING, 'UTF-8');
        curl_setopt($curl, CURLOPT_HTTPHEADER, ['Content-Type: application/json','Content-Length: '.strlen($field), 'sid:'.$this->session]);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_TIMEOUT, 10);
        curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36');
        curl_setopt($curl, CURLOPT_HEADER, false);
        $result = curl_exec($curl);
        curl_close($curl);
        if($this->session==null){
            return json_decode($result)->d;
        }else{
            return str_replace('\u000d\u000a','',$result);
        }
    }

    protected function login(){
        $login = json_encode(["pKluczUzytkownika" => $this->key]);
        $result = $this->makeCurl($login, $this->loginUrl);
        return $result;
    }

    public function checkNip($nip){

        if($this->session==null){
            $this->session = $this->login();
        }



        $searchData = json_encode([
            'jestWojPowGmnMiej' => true,
            'pParametryWyszukiwania' => [
                'AdsSymbolGminy' => null,
                'AdsSymbolMiejscowosci' => null,
                'AdsSymbolPowiatu' => null,
                'AdsSymbolUlicy' => null,
                'AdsSymbolWojewodztwa' => null,
                'Dzialalnosci' => null,
                'FormaPrawna' => null,
                'Krs' => null,
                'Krsy' => null,
                'NazwaPodmiotu' => null,
                'Nip' => $nip,
                'Nipy' => null,
                'NumerwRejestrzeLubEwidencji' => null,
                'OrganRejestrowy' => null,
                'PrzewazajacePKD' => false,
                'Regon' => null,
                'Regony14zn' => null,
                'Regony9zn' => null,
                'RodzajRejestru' => null,
                ]
            ]
        );

        $result = $this->makeCurl($searchData,$this->searchDataUrl);
        return $result;
    }


}

?>`

**Comment by PiotrCzarnik** [comment]
Panie Krzysztofie poniżej mój kod , proszę też o adres priv to prześlę mój klucz api .
`<?php
$nip = '1130089950';
$gus = new GusRegonApi();
$result = $gus->checkNip($nip);
echo $result;

class GusRegonApi{
//adresy produkcyjne
protected $loginUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
protected $searchDataUrl = 'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';
//adresy testowe
protected $loginTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/Zaloguj';
protected $searchDataTestUrl = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc/ajaxEndpoint/daneSzukaj';

//tutaj wpisan klucz do GUS - obecnie testowy
protected $key = "c2fb871634xxxxxxxxxx"; // "abcde12345abcde12345"; 
protected $session = null;

protected function makeCurl($field,$url){
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_POST, true);
    curl_setopt($curl, CURLOPT_POSTFIELDS, $field);
    curl_setopt($curl, CURLOPT_ENCODING, 'UTF-8');
    curl_setopt($curl, CURLOPT_HTTPHEADER, ['Content-Type: application/json','Content-Length: '.strlen($field), 'sid:'.$this->session]);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($curl, CURLOPT_TIMEOUT, 10);
    curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36');
    curl_setopt($curl, CURLOPT_HEADER, false);
    $result = curl_exec($curl);
    curl_close($curl);
    if($this->session==null){
        return json_decode($result)->d;
    }else{
        return str_replace('\u000d\u000a','',$result);
    }
}

protected function login(){
    $login = json_encode(["pKluczUzytkownika" => $this->key]);
    $result = $this->makeCurl($login, $this->loginUrl);
    return $result;
}

public function checkNip($nip){

    if($this->session==null){
        $this->session = $this->login();
    }



    $searchData = json_encode([
        'jestWojPowGmnMiej' => true,
        'pParametryWyszukiwania' => [
            'AdsSymbolGminy' => null,
            'AdsSymbolMiejscowosci' => null,
            'AdsSymbolPowiatu' => null,
            'AdsSymbolUlicy' => null,
            'AdsSymbolWojewodztwa' => null,
            'Dzialalnosci' => null,
            'FormaPrawna' => null,
            'Krs' => null,
            'Krsy' => null,
            'NazwaPodmiotu' => null,
            'Nip' => $nip,
            'Nipy' => null,
            'NumerwRejestrzeLubEwidencji' => null,
            'OrganRejestrowy' => null,
            'PrzewazajacePKD' => false,
            'Regon' => null,
            'Regony14zn' => null,
            'Regony9zn' => null,
            'RodzajRejestru' => null,
            ]
        ]
    );

    $result = $this->makeCurl($searchData,$this->searchDataUrl);
    return $result;
}

**Comment by KulaKrzysztof** [comment]
Po wpisaniu mojego klucza, dostaję zwrotnie dane firmy w XML. 
Mail kontaktowy: krzysztof@kula.xyz

**Comment by PiotrCzarnik** [comment]
Dzięki wielkie ; działa wszystko .
Opiszę poniżej o co chodziło 
Występując z wnioskiem do GUS podaje się IP serwera na którym będzie działał skrypt (jak powiedział mi programista z GUS-u , jest to tylko po to aby mieli dostęp serwisowy np. jeżeli byśmy odpytywali za często ) .
W moim przypadku dali mi klucz i jednocześnie zablokowali możliwość wysyłania zapytania z IP serwera który im podałem 👍 
Jednym słowem ,wszyscy mogli korzystać tylko nie ja .
Panie Krzysztofie , dzięki za pomoc , proszę podać paypal wesprę projekt .

**Comment by qman-web-development** [comment]
> A IP serwera zgadza się z tym zgłoszonym w GUS?

**Comment by qman-web-development** [comment]
> A IP serwera zgadza się z tym zgłoszonym w GUS?

a w jaki sposób mam zgłosić IP serwera? Na stronie można podać tylko adres email https://api.stat.gov.pl/Home/BdlApi i w odpowiedzi otrzymuje się klucz
