### ISSUE TITLE
Imię i nazwisko

### ISSUE THREAD

**Issue by pydanielthon** [KulaKrzysztof/GUS-API---PHP#5]
Cześć mam dwa pytania,

1. Da się pobrać imię i nazwisko na podstawie tego kodu?
2. Jak się odwołać do jednego elementu, np wyświetlić tylko adres

**Comment by KulaKrzysztof** [comment]
1. Imię nazwisko - kogo (DG, Spółka?)
2. Proszę doczytać czym jest JSON oraz XML.
