### ISSUE TITLE
Problem z pobraniem danych

### ISSUE THREAD

**Issue by sebastiankot** [KulaKrzysztof/GUS-API---PHP#6]
Dzień dobry,

Mam problem z pobraniem danych. Wpisałem tokeny, linki z API. Nie wyrzuca mi żadnego błędu. Komunikuje się przez AJAX w dataType mam **json**. Wychodzi mi wyjątek/error parsererror oraz SyntaxError: Unexpected end of JSON input.

Czy mógłby ktoś nakierować o co chodzi?

**Comment by KulaKrzysztof** [comment]
Dzień dobry,
Spowodowane to jest tym, że GUS zwraca XML, który zawiera JSON. Proszę sprawdzić co jest zwracane przez GUS i poprawnie się odwołać.
